name: Build plugin

on:
  push:
    branches:
      - "master"
    tags:
      - "*"

env:
  PLUGIN_NAME: ass-convert

jobs:
  build:
    permissions: write-all
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Build
        id: build
        run: |
          npm  install
          npm run build
          ls
          ls dist
          echo "::set-output name=tag_name::$(git tag --sort version:refname | tail -n 1)"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false
      - name: Upload win-version
        id: upload-win-version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ass-convert-win.exe
          asset_name: ass-convert-win.exe
          asset_content_type: application/octet-stream
      - name: Upload linux-version
        id: upload-linux-version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ass-convert-linux
          asset_name: ass-convert-linux
          asset_content_type: application/octet-stream
      - name: Upload mac-version
        id: upload-mac-version
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/ass-convert-macos
          asset_name: ass-convert-macos
          asset_content_type: application/octet-stream
